activeTheme: classic
siteName: Curso de Piano Online
description: Mentoria de Física Quântica e Metafísica aplicada à cocriação consciente da realidade. Desperte seu poder criador com Paula Franco.
keywords: curso de piano online, aprender piano, piano para iniciantes, piano adultos, método piano, curso teclado online
colorScheme: dark
